### ISSUE TITLE
建议直接换成winget

### ISSUE THREAD

**Issue by wherewhere** [Gaoyifei1011/GetStoreApp#1]
winget有一个专门调用winget的轮子，而且官方还写了一个demo，不过只有CPP的，我始终无法在cs上调用这个轮子，不知道作者能不能尝试把这个轮子跑起来。。。
https://github.com/microsoft/winget-cli/tree/master/tools%2FSampleWinGetUWPCaller

**Comment by Gaoyifei1011** [comment]
> winget有一个专门调用winget的轮子，而且官方还写了一个demo，不过只有CPP的，我始终无法在cs上调用这个轮子，不知道作者能不能尝试把这个轮子跑起来。。。 https://github.com/microsoft/winget-cli/tree/master/tools%2FSampleWinGetUWPCaller

感谢回复。这周我先解决一下那几个bug吧，之后我正好要学习一下c++（年底要考ccf），有时间顺手可以尝试转换成winget。

**Comment by wherewhere** [comment]
可怕，真的要换cpp吗？就不能研究一下让cs带起来轮子吗🤣

**Comment by Gaoyifei1011** [comment]
> 

有时间吧。现在我在上研一，学的是人工智能。你也应该了解这些专业大概会学一些什么内容。（Python、机器学习、深度学习等）。现在我的时间没有那么充裕，抽个时间让我研究一下吧，看看能不能让cs带起来轮子。

**Comment by Gaoyifei1011** [comment]
> 可怕，真的要换cpp吗？就不能研究一下让cs带起来轮子吗🤣

有时间吧。现在我在上研一，学的是人工智能。你也应该了解这些专业大概会学一些什么内容。（Python、机器学习、深度学习等）。现在我的时间没有那么充裕，抽个时间让我研究一下吧，看看能不能让cs带起来轮子。

**Comment by wherewhere** [comment]
还有就是commit简直太干净了，你确定还能记得每次更新了啥吗🤣

**Comment by Gaoyifei1011** [comment]
> 还有就是commit简直太干净了，你确定还能记得每次更新了啥吗🤣

有时候事太多，提交的时候到了半夜了，不带想今天更新的内容，所以直接按照日期省事了。以后的话我尽量提及更新的内容。

**Comment by Gaoyifei1011** [comment]
> 我成功在C#调用winget了！ https://github.com/wherewhere/SampleWinGetUWPCaller
> 
> ![image](https://user-images.githubusercontent.com/27689196/234892196-d750a0d0-c1ed-4174-adf6-28e844089356.png)

非常感谢，我有时间看一下（这个问题我先打开挂着）

**Comment by wherewhere** [comment]
[WinGetStore_0.0.0.0_x64_arm64.zip](https://github.com/Gaoyifei1011/GetStoreApp/files/11384472/WinGetStore_0.0.0.0_x64_arm64.zip)

胡乱写的 WinGet 客户端

**Comment by Gaoyifei1011** [comment]
> [WinGetStore_0.0.0.0_x64_arm64.zip](https://github.com/Gaoyifei1011/GetStoreApp/files/11384472/WinGetStore_0.0.0.0_x64_arm64.zip)
> 
> 胡乱写的 WinGet 客户端

AppInstallerCaller.WinRT （Cpp WinRT）这一部分也可以抹去了，直接纯c#写
由于.NET Core 5以上的版本并没有内置的C# WinRT支持，所以需要单独下载Nuget包Microsoft.Windows.CsWinRT。
打开项目的csproj文件，添加如下内容
<CsWinRTIncludes>Microsoft.Management.Deployment</CsWinRTIncludes>
<CsWinRTInputs Include="Microsoft.Management.Deployment.winmd" />（Winmd文件存放的实际路径）

![image](https://user-images.githubusercontent.com/49179966/236653223-27f381c9-b67f-4468-9697-e6fe05f5993f.png)

在Cpp Winrt 这一段代码是用来创建PackageManager的实例
使用c# 改写

            Guid guid = new Guid("C53A4F16-787E-42A4-B304-29EFFB4BF597");
            Guid iid = new Guid("00000000-0000-0000-C000-000000000046");
            Ole32Library.CoCreateInstance(&guid, IntPtr.Zero, CLSCTX.CLSCTX_ALL, &iid, out IntPtr obj);
            PackageManager packageManager = PackageManager.FromAbi(obj);
            List<PackageCatalogReference> catalogs = packageManager.GetPackageCatalogs().ToList();
            foreach (PackageCatalogReference item in catalogs)
            {
                Debug.WriteLine("===========================");
                Debug.WriteLine("Name:" + item.Info.Name);
                Debug.WriteLine("Argument:" + item.Info.Argument);
                Debug.WriteLine("LastUpdateTime" + item.Info.LastUpdateTime);
                Debug.WriteLine("Type:" + item.Info.Type);
            }
            Debug.WriteLine(catalogs.Count);

运行结果和相应的输出结果
![image](https://user-images.githubusercontent.com/49179966/236653537-6bdb1108-1d14-48d2-8434-da5ba1351491.png)

剩下的如法炮制即可
需要PInvoke CoCreateInstance函数

        [LibraryImport(Ole32, EntryPoint = "CoCreateInstance", SetLastError = true)]
        public static unsafe partial int CoCreateInstance(Guid* rclsid, IntPtr pUnkOuter, CLSCTX dwClsContext, Guid* riid, out IntPtr ppv);

**Comment by wherewhere** [comment]
你过时了，再看一眼我的项目，现在有C#版的了

**Comment by wherewhere** [comment]
还有尽量不要用指针，毕竟是unsafe

**Comment by Gaoyifei1011** [comment]
> 你过时了，再看一眼我的项目，现在有C#版的CreateInstance了 https://github.com/wherewhere/SampleWinGetUWPCaller/blob/main/AppInstallerCaller/WinGetProjectionFactory.cs

什么过时了，我看了，也是同样调用cocreateinstance了，有什么区别吗？
而且.net7的libraryimport不支持引用传递guid类型，所以改成了指针传递

**Comment by wherewhere** [comment]
.net7居然不能ref，.net6还能用呢

**Comment by wherewhere** [comment]
你可以看看这个项目
https://github.com/shmuelie/Shmuelie.WinRTServer

**Comment by Gaoyifei1011** [comment]
> .net7居然不能ref，.net6还能用呢 还有进程内通信的guid不要手写，直接获取guid，不然可能会出问题(不要问我怎么知道的

这个只是针对.net 7 的PInvoke源生成。
https://learn.microsoft.com/zh-cn/dotnet/standard/native-interop/pinvoke-source-generation

如果引用传递，就会出现这样的错误
![image](https://user-images.githubusercontent.com/49179966/236663177-8170b155-de89-4052-8411-47c3919805d7.png)

**Comment by Gaoyifei1011** [comment]
> 你可以看看这个项目 https://github.com/shmuelie/Shmuelie.WinRTServer

好的。

**Comment by wherewhere** [comment]
.net7居然不safe了，真是.net巨变，Windows解体

**Comment by Gaoyifei1011** [comment]
> .net7居然不safe了，真是.net巨变，Windows解体

也有可能是.net 7 的 P/Invoke源生成支持的不够完善吧，看.net 8 是什么情况吧。
而且微软的CsWin32生成的代码也是大量使用了指针😂

**Comment by wherewhere** [comment]
问题是.net6能用。。。

**Comment by Gaoyifei1011** [comment]
> 问题是.net6能用。。。

这，ms的锅，让他们修去吧😂😂

**Comment by wherewhere** [comment]
要是放在十年前.net5发布的时候aot都做完了，现在全都在磨蹭，真的是烂掉了

**Comment by cnbluefire** [comment]
> 你过时了，再看一眼我的项目，现在有C#版的CreateInstance了 https://github.com/wherewhere/SampleWinGetUWPCaller/blob/main/AppInstallerCaller/WinGetProjectionFactory.cs

https://github.com/microsoft/CsWinRT/blob/master/docs/interop.md#summary

文档表示GetObjectForIUnknown应该换成FromAbi，你才是过时的那个。
另外手写的iid是IUnknown接口的，FromAbi时内部有QueryInterface，你那个起手直接反射GetInterfaces才是比较难受的写法。

**Comment by wherewhere** [comment]
我是用UWP的，没有CSWinRT，而且CPP/WinRT本身就是直接获取Guid，不信你自己去看

**Comment by wherewhere** [comment]
而且微软的msstore就是用的GetObjectForIUnknown
https://devblogs.microsoft.com/ifdef-windows/the-journey-of-moving-from-cpp-winrt-to-csharp-in-the-microsoft-store/

**Comment by cnbluefire** [comment]
> 我是用UWP的，没有CSWinRT，而且CPP/WinRT本身就是直接获取Guid，不信你自己去看

cppwinrt是通过模板直接在编译期把GUID编进源码了，cswinrt也有类似的用法，你这纯纯运行时反射啊。
另外不管这里传入的guid是实际接口的iid还是iunknown的，cswinrt在构造对象时都会再调用一次QueryInterface，所以在cswinrt下面这里写实际iid就是脱裤子放屁。

**Comment by cnbluefire** [comment]
> 而且微软的msstore就是用的GetObjectForIUnknown https://devblogs.microsoft.com/ifdef-windows/the-journey-of-moving-from-cpp-winrt-to-csharp-in-the-microsoft-store/

我指的时你说的过时了，从时间上来说GetObjectForIUnknown才是过时方法，因为.net已经移除了内建的winrt interop，新版本的.net中GetObjectForIUnknown已经不支持winrt对象了。

**Comment by wherewhere** [comment]
反正我是抄winget的，人家传实际的我也传实际的
https://github.com/microsoft/winget-cli/blob/master/src/Microsoft.Management.Deployment.Projection/ClassesDefinition.cs

**Comment by wherewhere** [comment]
CS/WinRT直接返回object就行了，返回地址是.net native限制，然后直接as就完事了

**Comment by cnbluefire** [comment]
> 反正我是抄winget的，人家传实际的我也传实际的 https://github.com/microsoft/winget-cli/blob/master/src/Microsoft.Management.Deployment.Projection/ClassesDefinition.cs

如果知道原理，就明白这里不传实际的，后续步骤运行时或库会帮你用实际iid去转换或者验证，其实没差别。
 (T)Marshal.GetObjectForIUnknown(ptr)这句里，对RCW对象进行类型转换也会发生QueryInterface，都是自动的。

IUnknown接口相当于COM中的object，是所有COM对象都实现了的接口。在能确定从CLSID_PackageManager构造的COM对象一定实现了IPackageManager的情况下，这里传IUnknown没啥问题。但是在某些不确定某CLSID构造的COM对象是否实现某接口的时候，这里传具体接口可以提前验证，这种情况下是有收益的。

**Comment by wherewhere** [comment]
> https://github.com/microsoft/CsWinRT/blob/master/docs/interop.md#summary
> 
> 文档表示GetObjectForIUnknown应该换成FromAbi，你才是过时的那个。
> 另外手写的iid是IUnknown接口的，FromAbi时内部有QueryInterface，你那个起手直接反射GetInterfaces才是比较难受的写法。

还有我说的过时是指他没有发现我已经换成C#了，没说他写的过时了

**Comment by cnbluefire** [comment]
> CS/WinRT直接返回object就行了，返回地址是.net native限制，然后直接as就完事了

cswinrt是必须返回指针的，因为winrt对象不是RCW对象了。net core 3.1之前的版本才可以返回对象。

**Comment by wherewhere** [comment]
哦对了，话说你用过out of process的winrt吗，总是报错没有注册接口。。。
com真是太复杂了，如果可以像引用dll一样简单就好了

**Comment by cnbluefire** [comment]
> 

winmd文件只是提供了个声明，out of process是通过系统的MSRPC机制通信的，各种ID也是操作系统在管理的，所以完全不需要引用什么东西。我不太清楚原理，但是目前我知道的解决方案就是把winmd文件输出到appxmanifest.xml文件同级的目录，看起来运行的时候会自动注册winmd里的接口。

**Comment by wherewhere** [comment]
额，我说的意思是简化成直接点一下引用就能直接用了，现在太复杂了，要生成winmd，要注册，弄一个类出来千难万难。。。

**Comment by wherewhere** [comment]
就比如这个轮子
https://github.com/shmuelie/Shmuelie.WinRTServer

**Comment by cnbluefire** [comment]
> 额，我说的意思是简化成直接点一下引用就能直接用了，现在太复杂了，要生成winmd，要注册，弄一个类出来千难万难。。。

官方就没啥out of process的winrt对象的例子，这玩意儿甚至可以说是卡着bug在跑

**Comment by cnbluefire** [comment]
注册的部分可以放到appxmanifest里，至少比写注册表好多了。。。

**Comment by wherewhere** [comment]
微软有一个，是cpp/winrt和.net通信，那个实例太复杂了，我看不懂。。。
CS/WinRT有一个万年老贴，有人想要用C#实现，然后就没有然后了。。。

**Comment by cnbluefire** [comment]
如果不是为第三方软件提供服务，需要server被动启动的场景，通信直接走socket甚至http都好得多。COM通信这块太复杂了，到处都是坑。

通信也不是WinRT做的，是走的COM通信，系统给生成代理对象。这里有个特性是代理对象的iid和原对象是一致的，WinRT刚好只依赖iid，所以就有种卡着Bug在跑的感觉。但实际上系统有很多WinRT接口都是RPC的，从Debug输出里时不时蹦出来的RPC失败就能看出来。

**Comment by cnbluefire** [comment]
> winrt应该算是新一代的com吧，我现在感觉winrt/com更像是通信协议了。。。 com这种通信可以像引用类库一样和别的进程通信，不需要考虑什么序列化反序列化，过来就是一个好好的类，用起来特别方便，就是对创作者非常不友好。。。

实际上是系统帮你做了序列化反序列化，生成了代理对象，而且因为不是自己做的，很多细节微软也没给出来，遇到未知问题的调试过程比常见的ipc或者rpc复杂得多。。。

**Comment by wherewhere** [comment]
那是微软的问题了，反正我不用考虑序列化了，用起来好用就行了，不过就现在微软这种状态也不指望com能变得好用了

**Comment by wherewhere** [comment]
既然新版本发布了，这个问题就关掉吧

**Comment by Gaoyifei1011** [comment]
> 既然新版本发布了，这个问题就关掉吧

OK 非常感谢。
