### ISSUE TITLE
不适配 WIN10

### ISSUE THREAD

**Issue by Vixb1122** [Gaoyifei1011/GetStoreApp#10]
win 10 打开后页面不能点击

**Comment by Gaoyifei1011** [comment]
> win 10 打开后页面不能点击

收到，我抽个时间在Win10平台下测试一下吧，非常感谢反馈

**Comment by Gaoyifei1011** [comment]
> win 10 打开后页面不能点击

这个问题已经找到原因了，GetStoreApp主应用程序内调用的PrivateCreateCoreWindow创建的CoreWindow窗口，默认状态在Windows 11 22621+的窗口扩展样式包含WS_EX_Transparent（透明窗口），在Windows 10 1904x版本中并不包含这一扩展样式，故导致窗口无法接收窗口消息，从而导致应用窗口无法点击，这个bug在下一个版本中修复，您可以尝试拉取最新的代码编译使用修复后的版本，非常感谢。
![屏幕截图 2023-12-29 205154](https://github.com/Gaoyifei1011/GetStoreApp/assets/49179966/84fba96c-7225-4f8e-a1fe-d58addf8995d)
https://learn.microsoft.com/zh-cn/windows/win32/winmsg/extended-window-styles
