### ISSUE TITLE
网络链接异常

### ISSUE THREAD

**Issue by CocoTang1024** [Gaoyifei1011/GetStoreApp#11]
Windows 规格：
Windows 10 专业工作站版
22H2
19045.3758
下载内容出现如下报错，但是我实际上已经连接上了网络
![image](https://github.com/Gaoyifei1011/GetStoreApp/assets/75608560/c36d16a9-c8e9-4ee4-b083-024692d11c72)

**Comment by Gaoyifei1011** [comment]
> Windows 规格： Windows 10 专业工作站版 22H2 19045.3758 下载内容出现如下报错，但是我实际上已经连接上了网络 ![image](https://private-user-images.githubusercontent.com/75608560/331449558-c36d16a9-c8e9-4ee4-b083-024692d11c72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MTc4MDgsIm5iZiI6MTcxNTkxNzUwOCwicGF0aCI6Ii83NTYwODU2MC8zMzE0NDk1NTgtYzM2ZDE2YTktYzhlOS00ZWU0LWIwODMtMDI0NjkyZDExYzcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDAzNDUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljMTI0OTJlMjFlNzY0ZTY2ZjY2ZGMzZTdhOWU4ZTQ2MjNhMzEyYzQwZDFkZmM4YzQ4MjI1Mzc0NGFiOGU5ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xKr2QXe6Ugt4mPzx5DY8bfzbcuvTNAuSc5J1vx6eLqk)

目前这个选项您可以在设置-实验性功能-网络监控开关中关掉。之前测试中发现这是Windows runtime api的问题。
这个选项的引入是和aria2下载引擎在下载文件时，如果网络处于断开状态，aria2下载引擎处于长时间等待状态而不暂停下载。
4.0版本的开发已接近尾声，过几天要发布新下载引擎的4.0新版本，新引擎解决了这一问题，这个选项也将删除
过几天

**Comment by CocoTang1024** [comment]
好嘞

**Comment by Gaoyifei1011** [comment]
> 好嘞

或者您也可以自行下载现有代码编译4.0版本(版本号手动更新即可😂)

**Comment by Gaoyifei1011** [comment]
没有其他问题，issue即将关闭

**Comment by CocoTang1024** [comment]
> > 好嘞
> 
> 
> 
> 或者您也可以自行下载现有代码编译4.0版本(版本号手动更新即可😂)

哈哈😆我试试去 感谢🥹

**Comment by CocoTang1024** [comment]
> 没有其他问题，issue即将关闭

嗯嗯，没有其他问题了
