### ISSUE TITLE
GitHub 错拼为 Gtihub

### ISSUE THREAD

**Issue by realSNES** [Gaoyifei1011/GetStoreApp#12]
![image](https://github.com/Gaoyifei1011/GetStoreApp/assets/162039573/6d8389f7-4b92-42d1-a335-9805c212aa55)

**Comment by Gaoyifei1011** [comment]
> ![image](https://private-user-images.githubusercontent.com/162039573/331680051-6d8389f7-4b92-42d1-a335-9805c212aa55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMDA5NjUsIm5iZiI6MTcxNjAwMDY2NSwicGF0aCI6Ii8xNjIwMzk1NzMvMzMxNjgwMDUxLTZkODM4OWY3LTRiOTItNDJkMS1hMzM1LTk4MDVjMjEyYWE1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOFQwMjUxMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZmI4MDM3ZmViMjk2MDZlMDBkMWZkZWE5MDUwYWIzZDA0NjFmMjRiOWVjMzA3MTdjODBkODZmZjU2YmYzMTZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.txhyW6lhSx2yzstD7UbuJOF53nObTCwFffKTFm8ZAEs)

https://github.com/Gaoyifei1011/GetStoreApp/commit/991978b158ea4235b053721dc98c413775b8cfc3
字符串问题已解决，没有其他问题的话，issues即将关闭。
感谢您对该项目问题错误的指正。

**Comment by Gaoyifei1011** [comment]
修复的内容将在4.0版本中更新，感谢支持
