### ISSUE TITLE
程序无法正常显示

### ISSUE THREAD

**Issue by cgykcftyi** [Gaoyifei1011/GetStoreApp#22]
![image](https://github.com/user-attachments/assets/e9ec3f7f-f81f-469c-8d0e-0c53d448b7a2)
在任务栏小窗可以看到程序在运行，但就是不在正常窗口运行

**Comment by Gaoyifei1011** [comment]
> ![image](https://private-user-images.githubusercontent.com/144046679/384374105-e9ec3f7f-f81f-469c-8d0e-0c53d448b7a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNzYxMjgsIm5iZiI6MTczMTA3NTgyOCwicGF0aCI6Ii8xNDQwNDY2NzkvMzg0Mzc0MTA1LWU5ZWMzZjdmLWY4MWYtNDY5Yy04ZDBlLTBjNTNkNDQ4YjdhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOFQxNDIzNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YmIyOWE5MmY2OTI2MWUxZWQ1MWVmOGY5NTgzMjVlZmZhNWNiNjQxNzAwMTY1MTFhNWY2Y2M0YTA0MWUzODA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bzEPt17hGvu675BM-HzCIKiZ8XlId2yslQzGj4jwCuE) 在任务栏小窗可以看到程序在运行，但就是不在正常窗口运行

想问一下这个现象是怎么发生的，我很好奇。是应用程序最小化后，点击图标窗口不能正常显示还是其他的什么问题？😂

**Comment by cgykcftyi** [comment]
> > ![image](https://private-user-images.githubusercontent.com/144046679/384374105-e9ec3f7f-f81f-469c-8d0e-0c53d448b7a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNzYxMjgsIm5iZiI6MTczMTA3NTgyOCwicGF0aCI6Ii8xNDQwNDY2NzkvMzg0Mzc0MTA1LWU5ZWMzZjdmLWY4MWYtNDY5Yy04ZDBlLTBjNTNkNDQ4YjdhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOFQxNDIzNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YmIyOWE5MmY2OTI2MWUxZWQ1MWVmOGY5NTgzMjVlZmZhNWNiNjQxNzAwMTY1MTFhNWY2Y2M0YTA0MWUzODA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bzEPt17hGvu675BM-HzCIKiZ8XlId2yslQzGj4jwCuE) 在任务栏小窗可以看到程序在运行，但就是不在正常窗口运行
> 
> 想问一下这个现象是怎么发生的，我很好奇。是应用程序最小化后，点击图标窗口不能正常显示还是其他的什么问题？😂

刚开始安了.net8最新稳定版还能正常使用一两次，之后再启动就成这样了，重装也不行

**Comment by cgykcftyi** [comment]
删除后再安装又正常了

**Comment by Gaoyifei1011** [comment]
> 删除后再安装又正常了

根据您的描述，我猜测大概是窗口的坐标位置可能跑到了窗口屏幕边界外，所以导致窗口显示不出来。
如果您下次遇到这样的问题，您可以把鼠标移到任务栏的图标，如果任务栏图标的小窗能正常显示，您可以点击该小窗的右键菜单，然后让其最大化后并还原窗口应该就能正常显示了

**Comment by Gaoyifei1011** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/144046679/384374105-e9ec3f7f-f81f-469c-8d0e-0c53d448b7a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNzYxMjgsIm5iZiI6MTczMTA3NTgyOCwicGF0aCI6Ii8xNDQwNDY2NzkvMzg0Mzc0MTA1LWU5ZWMzZjdmLWY4MWYtNDY5Yy04ZDBlLTBjNTNkNDQ4YjdhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOFQxNDIzNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YmIyOWE5MmY2OTI2MWUxZWQ1MWVmOGY5NTgzMjVlZmZhNWNiNjQxNzAwMTY1MTFhNWY2Y2M0YTA0MWUzODA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bzEPt17hGvu675BM-HzCIKiZ8XlId2yslQzGj4jwCuE) 在任务栏小窗可以看到程序在运行，但就是不在正常窗口运行
> > 
> > 
> > 想问一下这个现象是怎么发生的，我很好奇。是应用程序最小化后，点击图标窗口不能正常显示还是其他的什么问题？😂
> 
> 刚开始安了.net8最新稳定版还能正常使用一两次，之后再启动就成这样了，重装也不行

纠正一下。这个项目使用的是.NET9 with native aot编译，不是 net8，编译后生成的是本机代码，这意味着应用程序在运行过程中，不需要 net 运行时

**Comment by Gaoyifei1011** [comment]
> 删除后再安装又正常了

![{05E3500A-8810-4FEB-AACD-1D304B471B3F}](https://github.com/user-attachments/assets/1684acdf-4b71-414e-8103-bc64eddca454)
就是图片上对应的右键菜单
