### ISSUE TITLE
感觉这个功能实现还挺简单的

### ISSUE THREAD

**Issue by Goojoe** [Gaoyifei1011/GetStoreApp#3]
前几天用Python写,一会就写完了
1. 请求API
2. 过滤无用文件,下载文件
3. 创建安装脚本
4. 压缩打包

不过UI版也有对应的优势,看介绍说有打算做直接安装的,那也挺好的,Microsoft的网络是真不稳定,MS-Store真心不好用

**Comment by Gaoyifei1011** [comment]
其实这个该怎么说呢，在构建之前Python脚本，powershell脚本我都见过。前几个月闲来无事，就学一学wpf/uwp/winui。之后在写的过程中发现内容越来越多，所以就成了现在这个样子😂😂。
我也在说明中描述了，只是学习c#而构建的一个项目，代码可能有点乱，而且在实现完成后基本上也不会大范围宣传。
此外现在是我本人刚上研究生的初期，有大量闲余的时间，所以最近更新比较频繁，想早点把所有内容都构建完成。在这个内容构建完成后基本上就进入维护阶段了，不会有大的更新。

**Comment by Gaoyifei1011** [comment]
感谢你的评论
