### ISSUE TITLE
Releses体积太大

### ISSUE THREAD

**Issue by Goojoe** [Gaoyifei1011/GetStoreApp#4]
> 接上一条issue,保持issue整洁,不同主题应该单开issue

很简单的脚本就能实现,不是很理解为什么能有227Mb的大小,作为一款工具应用,这不太合理

我看了一下,你好像内嵌了没用的功能:访问网页版 跳转浏览器更加合理,内嵌性能得不到保证

**Comment by Gaoyifei1011** [comment]
你看到的releases的zip压缩文件中不仅包含了项目的安装包文件（msix） 还有visual studio打包应用的一些依赖框架，比如Windows app sdk安装包等等。
这个压缩包是在release模式下打压缩包的所有文件
实际上解压后的安装包文件大约在120MB左右。
应用是使用Windows app sdk （.net6.0）框架构建的，项目使用了自包含模式(self-contained)，打包时将net框架也一并打包。
而且目前版本的Windows app sdk 1.1没有提供il修剪，不能删剪掉那些不使用的库，微软说il修剪在1.2版本中支持(现在好像只能裁剪bcl库)，等到1.2版本应该会有一个明显的缩减。

**Comment by Gaoyifei1011** [comment]
打包后的msixbundle文件在100MB左右（包含x86，x64两个平台)，安装后应用大小好像在50MB左右，如果不使用自包含，打包大约在20MB左右。

**Comment by Goojoe** [comment]
原来是这样,把一些框架都打包进去了,GUI和兼容多版本的通病

**Comment by Gaoyifei1011** [comment]
> 原来是这样,把一些框架都打包进去了,GUI和兼容多版本的通病

没办法，微软的东西，你懂的。当然了was的应用也可以用c++实现，内存可控，体积也小。（可惜我目前不会）

**Comment by Gaoyifei1011** [comment]
这个版本已经分成了两个部分了，一个是应用的安装包msixbundle文件，熟悉UWP应用安装的可以直接使用这个文件快速安装，不熟悉的下载完整包按照说明快速安装。
was 1.2可能会提供IL修剪支持，到时候应用的安装包可能会可能会进一步缩小。
