### ISSUE TITLE
离线状态强制下载 或 代理下载

### ISSUE THREAD

**Issue by Goojoe** [Gaoyifei1011/GetStoreApp#5]
> 微软检测网络的逻辑很奇怪,经常有网也说没网,有些时候我必须要挂梯子下载,它还是检测断网
> 使用解除UWP网络回环工具也是如此
> 这个问题第一次用就出现了,当时没想起来提issue

解决这个应该有下面两个方法

1. 加入离线状态强制下载
2. 代理下载,Aria2自带

**Comment by Gaoyifei1011** [comment]
感谢您提出的问题。
关于这个问题，我不知道应该怎么说。这可能是一个老生常谈的问题吧。之前在Windows 10中，也出现过这样的新闻，网上也有类似的解决方法。

不太清楚您连接的是什么样的网络，我这里不管是移动流量，移动WIFI，还是学校的校园网，都没有您说的上述情况。
也许您可能处于特殊的工作环境，或者是电脑开启了代理服务等等，才造成这样的状况。
检测网络状态时会链接到微软的服务器，如果链接微软服务器异常，那么大概率也有可能不能正常访问Microsoft Store。甚至您正常获取到下载链接，也可能不能正常下载（下载链接也是基于微软服务器提供的。 ）    
最好的方法是检查一下您的网络配置，是否存在着一些特殊设置。
 
之所以要添加网络检测，是因为在下载过程中，如果发生了网络异常，Aria2并不会在一定时间内中断下载，它总是会一直显示下载速度为0，如果是这样就会阻塞下载队列。且获取到的这个链接具有时效性，如果发生了超时，即使在网络恢复正常的情况下，这个文件也不能继续下载。所以才加入了一个这样的检测方法，必须要确保网络正常的情况下下载。         

关于第一个方法，我可能不太会采取，如果在“离线状态”下加入强制下载，可能会发生一些我意想不到的BUG。
关于第二个，可能会在之后的版本（也许是基于0.6.0.0的修复版本，也许是0.7.0.0版本）中将Aria2的配置文件（Aria2.conf）放入到缓存目录中，并在设置中添加一个快速入口方便访问，这样的话就可以自定义配置文件来实现相应的需求了。  （安装目录中的文件用来初始化或恢复默认设置使用。）

**Comment by Gaoyifei1011** [comment]
> > 微软检测网络的逻辑很奇怪,经常有网也说没网,有些时候我必须要挂梯子下载,它还是检测断网
> > 使用解除UWP网络回环工具也是如此
> > 这个问题第一次用就出现了,当时没想起来提issue
> 
> 解决这个应该有下面两个方法
> 
> 1. 加入离线状态强制下载
> 2. 代理下载,Aria2自带

![image](https://user-images.githubusercontent.com/49179966/197731189-72f571cb-5b77-4a40-b448-a9f3a284ba61.png)

https://github.com/Gaoyifei1011/GetStoreApp/commit/ff6cd8854d908d7952e9cd8b7fd647329c33b1cc
现在已经将这些选项放到实验性功能中了，按照需求可以自定义设置，如果出现异常请恢复到默认值。
