### ISSUE TITLE
Empty release?

### ISSUE THREAD

**Issue by Chinesebg** [Gaoyifei1011/GetStoreApp#6]
这个uwp做得很好哇
但为啥0.7.2.0为空？![Screenshot_20221203-220603_GitHub.png](https://user-images.githubusercontent.com/88040372/205444911-b44ff939-ba64-4fe8-b547-6117243adb1e.png)

**Comment by Gaoyifei1011** [comment]
![image](https://user-images.githubusercontent.com/49179966/205446604-619f70f0-fde0-4ca8-ad0c-17eb323d1082.png)
![image](https://user-images.githubusercontent.com/49179966/205446636-df7af990-2dc8-4424-b5ec-08560fbe96dc.png)
不应该啊

**Comment by Gaoyifei1011** [comment]
> 这个uwp做得很好哇 但为啥0.7.2.0为空？![Screenshot_20221203-220603_GitHub.png](https://user-images.githubusercontent.com/88040372/205444911-b44ff939-ba64-4fe8-b547-6117243adb1e.png)

你可以检查一下发生了什么😂😂😂😂

**Comment by Gaoyifei1011** [comment]
> 这个uwp做得很好哇 但为啥0.7.2.0为空？![Screenshot_20221203-220603_GitHub.png](https://user-images.githubusercontent.com/88040372/205444911-b44ff939-ba64-4fe8-b547-6117243adb1e.png)

![Screenshot_2022-12-03-22-49-39-791_com android br](https://user-images.githubusercontent.com/49179966/205446902-348a3bb4-aa65-4d95-8af3-0ee9c2d6c597.jpg)
这是我在游客模式下测试的结果，正常显示

**Comment by Gaoyifei1011** [comment]
> 这个uwp做得很好哇 但为啥0.7.2.0为空？![Screenshot_20221203-220603_GitHub.png](https://user-images.githubusercontent.com/88040372/205444911-b44ff939-ba64-4fe8-b547-6117243adb1e.png)

刚才看了一下，可能是因为网络的问题吧，有一个重复的版本，显示成了草稿(Draft)，您检查一下吧，草稿版本已经删除了

**Comment by Chinesebg** [comment]
> > 这个uwp做得很好哇 但为啥0.7.2.0为空？![Screenshot_20221203-220603_GitHub.png](https://user-images.githubusercontent.com/88040372/205444911-b44ff939-ba64-4fe8-b547-6117243adb1e.png)
> 
> ![Screenshot_2022-12-03-22-49-39-791_com android br](https://user-images.githubusercontent.com/49179966/205446902-348a3bb4-aa65-4d95-8af3-0ee9c2d6c597.jpg) 这是我在游客模式下测试的结果，正常显示

好了，估计是网络问题，但还是感谢！！
