### ISSUE TITLE
1.6.501.0_x86_x64_arm64.msixbundle 提示证书错误

### ISSUE THREAD

**Issue by Mosney** [Gaoyifei1011/GetStoreApp#7]
无法验证此应用包的发布者证书。请与系统管理员或应用开发人员联系，以获取具有验证证书的新应用包。必须验证应用包中签名的根证书和所有直接证书(0x800B010A)

**Comment by Gaoyifei1011** [comment]
> 无法验证此应用包的发布者证书。请与系统管理员或应用开发人员联系，以获取具有验证证书的新应用包。必须验证应用包中签名的根证书和所有直接证书(0x800B010A)

https://blog.csdn.net/qq_36237810/article/details/110238783
你也许需要参考这个步骤

**Comment by Gaoyifei1011** [comment]
> 无法验证此应用包的发布者证书。请与系统管理员或应用开发人员联系，以获取具有验证证书的新应用包。必须验证应用包中签名的根证书和所有直接证书(0x800B010A)

**Comment by zhuxb711** [comment]
其实是说明不到位，单个msixbundle是用于已安装的用户的升级安装，所谓完整版就是带证书带符号的，侧载安装没有可信签名所以如果是首次安装的安装不了。至于描述的“快速安装”就词不达意了，普通用户根本不了解其中的区别。

**Comment by zhuxb711** [comment]
我的意思是你需要在Release部分中注明什么时候下载misxbundle什么时候下载zip，而不是用“快速安装”这种模糊的语言表达，当用户无法区分的时候他们往往会选择  更快速/大小更小 的选项。你的这种表达只有开发过WAS/UWP应用的开发者才看得懂。表达示例：

`首次安装时请下载XXX.zip`
```
<建议配图>
1. 解压下载的XXX.zip
2. 进入文件夹XXX
3. 找到文件Install.ps1
4. 右键点击Install.ps1选择 使用Powershell运行
5. 跟随Powershell的指示，若询问是否允许执行/导入证书，请选择是，直至完成安装
6. 后续更新发布时请直接下载并使用XXX.msixbundle双击升级即可，无需再次下载 XXX.zip 版本
```

`已安装之前发布的任意版本，请下载XXX.msixbundle`
```
<建议配图>
1. 双击XXX.msixbundle
2. 应用程序安装器应当自动打开
3. 点击右下角的升级按钮即可升级至最新版本
```

**Comment by code4lala** [comment]
看起来最新发布的release仍然是 `快速安装` 的表述，建议置顶该issue

**Comment by Gaoyifei1011** [comment]
> 看起来最新发布的release仍然是 `快速安装` 的表述，建议置顶该issue

已经更新了，前几天有事情没来的及看，抱歉。
安装描述已经更新，并附带具体的安装步骤，如果需要带引导图的安装步骤，可参考酷安UWP的链接（已在Release页面中添加酷安UWP github页面链接）

**Comment by code4lala** [comment]
> ④安装*.cer证书到本地计算机→受信任的根证书颁发机构。项操作需要用到管理员权限，如果您安装证书时没有用到该权限，则可能是因为您将证书安装到了错误的位置或者您使用的是超级管理员账户

这一步的`*.cer证书`需要从release的zip包中获取，但是实际上安装完证书之后就可以直接双击msixbundle安装了，建议在release页面直接把cer证书也单独上传一份，这样只需要下载cer证书和msixbundle就可以了，不需要下载133MB的zip包了。

**Comment by Gaoyifei1011** [comment]
> > ④安装*.cer证书到本地计算机→受信任的根证书颁发机构。项操作需要用到管理员权限，如果您安装证书时没有用到该权限，则可能是因为您将证书安装到了错误的位置或者您使用的是超级管理员账户
> 
> 这一步的`*.cer证书`需要从release的zip包中获取，但是实际上安装完证书之后就可以直接双击msixbundle安装了，建议在release页面直接把cer证书也单独上传一份，这样只需要下载cer证书和msixbundle就可以了，不需要下载133MB的zip包了。

OK。收到，一会我改一下分发的内容，但是为了以防在线依赖框架包下载失败的问题，故保留zip压缩包，谢谢
