### ISSUE TITLE
UI细节问题

### ISSUE THREAD

**Issue by zhuxb711** [Gaoyifei1011/GetStoreApp#8]
1. Width过小时相关文字被裁剪且TextTrimming未设置为CharacterEllipsis，不具备足够的提示以提醒用户文字未完全展示，几乎所有文字均使用裁剪模式即TextTrimming=None
![image](https://github.com/Gaoyifei1011/GetStoreApp/assets/42038175/169e05ba-7409-4f33-a331-5941d156e51e)
![image](https://github.com/Gaoyifei1011/GetStoreApp/assets/42038175/df3e0e29-ed00-45bc-a417-26f881968ea4)

2. Width足够时仍然弹出ToolTip，完全没有必要
![image](https://github.com/Gaoyifei1011/GetStoreApp/assets/42038175/59c4e06f-53eb-4b30-92aa-c7d7e0f75807)

3. 使用英文语言时，DateTimeOffset格式化仍然使用系统语言默认的格式化而不是跟随应用内语言BCP-47规定的日期格式化方式
![image](https://github.com/Gaoyifei1011/GetStoreApp/assets/42038175/60a9c104-b751-4db5-80ef-b35eff80d6d1)

**Comment by zhuxb711** [comment]
补：此处文字直接裁剪而没有换行
![image](https://github.com/Gaoyifei1011/GetStoreApp/assets/42038175/be6b9095-99fb-435a-bb76-95b8979dbde4)

**Comment by Gaoyifei1011** [comment]
> 1. Width过小时相关文字被裁剪且TextTrimming未设置为CharacterEllipsis，不具备足够的提示以提醒用户文字未完全展示，几乎所有文字均使用裁剪模式即TextTrimming=None
>    ![image](https://user-images.githubusercontent.com/42038175/260349713-169e05ba-7409-4f33-a331-5941d156e51e.png)
>    ![image](https://user-images.githubusercontent.com/42038175/260350006-df3e0e29-ed00-45bc-a417-26f881968ea4.png)
> 2. Width足够时仍然弹出ToolTip，完全没有必要
>    ![image](https://user-images.githubusercontent.com/42038175/260349808-59c4e06f-53eb-4b30-92aa-c7d7e0f75807.png)
> 3. 使用英文语言时，DateTimeOffset格式化仍然使用系统语言默认的格式化而不是跟随应用内语言BCP-47规定的日期格式化方式
>    ![image](https://user-images.githubusercontent.com/42038175/260354065-60a9c104-b751-4db5-80ef-b35eff80d6d1.png)

关于问题1，2，让我考虑一下吧，看看有没有什么好的解决方案。
问题3，关于这个语言BCP-47规定的日期格式化，我还得需要学习一下，如果可以的话，我会尽快尝试解决这个问题。

**Comment by Gaoyifei1011** [comment]
> 补：此处文字直接裁剪而没有换行 ![image](https://user-images.githubusercontent.com/42038175/260354513-be6b9095-99fb-435a-bb76-95b8979dbde4.png)

这个问题感谢提醒，下个版本修复

**Comment by zhuxb711** [comment]
设置TextTrimming="CharacterEllipsis"之后，文字超出部分显示 ...
![image](https://github.com/Gaoyifei1011/GetStoreApp/assets/42038175/450ae2ae-5863-42ad-b4dd-770db5d36247)

**Comment by zhuxb711** [comment]
你这实际上越写越麻烦了，加个名称都是很快的事情，XAML这就是家常便饭。当然我上面的XAML是DataTemplate中拿出来的所以也没多少，你这个App能有多少TextBlock，几十个顶天了吧

**Comment by Gaoyifei1011** [comment]
嗯。。我考虑一下吧

**Comment by zhuxb711** [comment]
???
为什么你仿佛在有理有据的说一些错误的结论？

System.Security.Principal不需要安装额外Nuget包，它是.Net 6/7的标准组件之一

**Comment by zhuxb711** [comment]
> 这样的应用我猜测肯定是需要严格的管理员模式检测的

不对，主页Pin的是Uwp版，Uwp运行于Low IL级别不可能提升为管理员权限，所以Uwp不存在这个问题。(WAS版你看不到，是闭源的）

我知道PackageManager的非ForUser版本都是需要提权的，也正因为如此，你这样写是对API的错误利用，是不可靠的方式。

（关于PackageManager我相信我更有发言权，因此你无需解释为什么你要这么写，我要是看不懂我就不评论了。Tips: 你正在写还没完工的东西RX早就实现了）

**Comment by Gaoyifei1011** [comment]
> > 这样的应用我猜测肯定是需要严格的管理员模式检测的
> 
> 不对，主页Pin的是Uwp版，Uwp运行于Low IL级别不可能提升为管理员权限，所以Uwp不存在这个问题。(WAS版你看不到，是闭源的）
> 
> 我知道PackageManager的非ForUser版本都是需要提权的，也正因为如此，你这样写是对API的错误利用，是不可靠的方式。
> 
> （关于PackageManager我相信我更有发言权，因此你无需解释为什么你要这么写，我要是看不懂我就不评论了。Tips: 你正在写还没完工的东西RX早就实现了）

那么对不起了，我写的应用主要是面向我使用的（只不过是顺手挂在我的Github主页下），您有您更好的实现方式，和我有什么关系呢？

**Comment by zhuxb711** [comment]
> WinRT失效
根本原因是WinRT一开始为Uwp设计，Uwp无法以任何方式提权到管理员权限，WinRT设计时从不考虑管理员权限下的运行问题，它不能用也是很正常的，因此你应该切换到Win32 API去完成这些事情。

疑问：如果你不愿意用Win32 API，也不愿意使用管理员权限，那你切换到WAS而不是在Uwp上开发的原因是什么

**Comment by zhuxb711** [comment]
> > > 这样的应用我猜测肯定是需要严格的管理员模式检测的
> 
> > 
> 
> > 不对，主页Pin的是Uwp版，Uwp运行于Low IL级别不可能提升为管理员权限，所以Uwp不存在这个问题。(WAS版你看不到，是闭源的）
> 
> > 
> 
> > 我知道PackageManager的非ForUser版本都是需要提权的，也正因为如此，你这样写是对API的错误利用，是不可靠的方式。
> 
> > 
> 
> > （关于PackageManager我相信我更有发言权，因此你无需解释为什么你要这么写，我要是看不懂我就不评论了。Tips: 你正在写还没完工的东西RX早就实现了）
> 
> 
> 
> 那么对不起了，我写的应用主要是面向我使用的（只不过是顺手挂在我的Github主页下），您有您更好的实现方式，和我有什么关系呢？

啧啧啧
我只是指出你说的东西不对，那个玩意不需要额外的Nuget包就能用，你就开始摆了是吧，当然你全部的Project都与我无关好吧
