### ISSUE TITLE
增加关于“PowerShell：因为在此系统上禁止运行脚本”的描述

### ISSUE THREAD

**Issue by Goojoe** [Gaoyifei1011/GetStoreApp#9]
计算机上启动 Windows PowerShell 时，执行策略很可能是 Restricted（默认设置）。

Restricted 执行策略不允许任何脚本运行。  
AllSigned 和 RemoteSigned 执行策略可防止 Windows PowerShell 运行没有数字签名的脚本。

可以使用以下命令在不更改执行策略时运行脚本（需要管理员权限）
```
powershell -ExecutionPolicy ByPass -File "Install.ps1"
```
在Releases添加关于这个的描述吧

**Comment by Gaoyifei1011** [comment]
好的，收到，非常感谢。我一会修改一下

**Comment by Gaoyifei1011** [comment]
已在release notes中更新，该Issue关闭。
